---
# tasks file for nginx
#
- name: disbled selinux task
  ansible.posix.selinux:
    state: disabled

- name: enabled http service task
  ansible.builtin.firewalld:
    immediate: true
    permanent: true
    service: http
    state: enabled

- name: enabled https service task
  ansible.builtin.firewalld:
    immediate: true
    permanent: true
    service: https
    state: enabled

- name: deploy nginx server task
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: started nginx service task
  ansible.builtin.systemd:
    enabled: true
    name: nginx
    state: started

- name: nginx config file task
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx service handler
