---
# tasks file for nginx
#
- name: disbled selinux task
  ansible.posix.selinux:
    state: disabled

- name: started firewalld task
  ansible.builtin.systemd:
    name: firewalld
    state: started

- name: enabled http service task
  ansible.builtin.firewalld:
    immediate: true
    permanent: true
    service: http
    state: enabled

- name: enabled https service task
  ansible.builtin.firewalld:
    immediate: true
    permanent: true
    service: https
    state: enabled

- name: deploy nginx server task
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - nginx-all-modules

- name: create tcp stream directory task
  ansible.builtin.file:
    path: /etc/nginx/tcp.d
    state: directory

- name: started nginx service task
  ansible.builtin.systemd:
    enabled: true
    name: nginx
    state: started

- name: nginx config file task
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx service handler

- name: copy kube-apiserver config task
  ansible.builtin.template:
    src: kube-apiserver.conf.j2
    dest: /etc/nginx/tcp.d/kube-apiserver.conf
  notify: restart nginx service handler
  when: kube_apiserver
