---
# tasks file for ksysctl
#
- name: copy ksys.conf task
  ansible.builtin.copy:
    src: ksys.conf
    dest: /etc/sysctl.d/ksys.conf
  register: copyResult

- name: reboot system task
  reboot:
  when: copyResult.changed
