#!/usr/bin/env playbook
---
- name: deploy kubernetes cluster play
  hosts: kmasters:knodes
  become: true
  gather_facts: true
  vars_files:
    - variables.yaml
  roles:
    - role: kubernetes
      when: addWorker
  tasks:
    - name: print join worker command task
      ansible.builtin.shell: kubeadm token create --print-join-command
      environment:
        KUBECONFIG: "{{ configFilePath }}/admin.conf"
      register: join_worker_command
      delegate_to: "{{ masterInitial }}"
      run_once: true

    - name: join worker task
      ansible.builtin.shell: "{{ join_worker_command.stdout }}"
      when: addWorker
