---
# tasks file for firewalld
#
- name: disabled firewalld task
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ open_ports }}"
