---
# tasks file for docker
#
#- name: create container data directory task
#  ansible.builtin.file:
#    path: "{{ containerDataDir }}"
#    state: directory

- name: add docker official dnf repo task
  ansible.builtin.yum_repository:
    name: docker-ce
    description: containerd repo
    baseurl: https://mirrors.aliyun.com/docker-ce/linux/centos/$releasever/$basearch/stable
    gpgcheck: false
    
- name: remove older versions task
  ansible.builtin.dnf:
    name: 
      - docker
      - docker-client
      - docker-common
      - docker-logrotate
      - docker-engine
    state: absent
    
- name: install docker package task
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - docker-buildx-plugin
      - containerd.io      
    state: present

- name: setting ulimit for docker task
  ansible.builtin.lineinfile:
    path: /usr/lib/systemd/system/docker.service
    regexp: ^ExecStart=/usr/bin/dockerd
    line: ExecStart=/usr/bin/dockerd --default-ulimit nofile=65536:65536 -H fd:// --containerd=/run/containerd/containerd.sock
    
- name: configure the daemon.json file task  
  # defines the container's data directory
  # defines the ali cloud mirror acceleration for pulling foreign mirrors
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0644

- name: started docker service task
  ansible.builtin.systemd:
    enabled: true
    name: docker
    state: started
    daemon_reload: true
